# Generated by Django 3.2 on 2023-03-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_picture',
            field=models.ImageField(null=True, upload_to='display_pics'),
        ),
    ]
