# Generated by Django 3.2 on 2023-03-02 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230302_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetail',
            name='weight',
        ),
        migrations.CreateModel(
            name='PatientMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.IntegerField(choices=[(1, 'Blood Pressure'), (2, 'Heart Rate'), (3, 'Blood Sugar Level'), (4, 'Weight')], null=True)),
                ('value', models.CharField(max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
