# Generated by Django 3.2 on 2023-03-02 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_patientmedicalhistory_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
