# Generated by Django 3.2 on 2023-03-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_patientdetail_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='attribute',
            field=models.IntegerField(choices=[(1, 'Blood Pressure'), (2, 'Heart Rate'), (3, 'Blood Sugar Level'), (4, 'Weight'), (5, 'Height')], null=True),
        ),
    ]
