# Generated by Django 3.2 on 2023-03-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='disease_images'),
        ),
    ]
