# Generated by Django 3.2 on 2023-03-02 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disease_management', '0002_alter_disease_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPersonalizedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.IntegerField(choices=[(1, 'Medications'), (2, 'Diet'), (3, 'Exercise')], default=1)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('frequency', models.IntegerField(choices=[(1, 'Day'), (2, 'Hours')], default=2)),
                ('magnitude', models.PositiveIntegerField(default=1)),
                ('value', models.CharField(blank=True, max_length=32, null=True)),
                ('plan_status', models.IntegerField(choices=[(1, 'Active'), (2, 'Pause Reminders'), (3, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
