# Generated by Django 3.2 on 2023-03-02 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disease_management', '0003_patientpersonalizedplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientpersonalizedplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientpersonalizedplan',
            name='notification_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientpersonalizedplan',
            name='notification_heading',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DiseaseDefaultPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_plan', models.TextField(blank=True, null=True)),
                ('diet_plan', models.TextField(blank=True, null=True)),
                ('medication_plan', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease_management.disease')),
            ],
        ),
    ]
