# Generated by Django 3.2 on 2023-03-02 13:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease_management', '0005_alter_diseasedefaultplan_diet_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasedefaultplan',
            name='exercise_plan',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diseasedefaultplan',
            name='medication_plan',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientpersonalizedplan',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
