# Generated by Django 3.2 on 2023-03-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_management', '0006_auto_20230302_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientpersonalizedplan',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'Day'), (2, 'Hours'), (3, 'Minutes')], default=2),
        ),
    ]
