# Generated by Django 3.2 on 2023-03-02 19:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_management', '0007_alter_patientpersonalizedplan_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasedefaultplan',
            name='monitoring',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientpersonalizedplan',
            name='plan',
            field=models.IntegerField(choices=[(1, 'Medications'), (2, 'Diet'), (3, 'Exercise'), (4, 'Monitoring'), (5, 'Others')], default=1),
        ),
    ]
