# Generated by Django 3.2 on 2023-03-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.IntegerField(choices=[(1, 'Read'), (2, 'Ignored'), (3, 'No Action')], default=3),
        ),
    ]
