# Generated by Django 3.2 on 2023-03-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20230302_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsscheduler',
            name='is_triggered',
        ),
        migrations.AddField(
            model_name='notificationsscheduler',
            name='last_triggered_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
